# Generated by Django 4.2.3 on 2023-10-06 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_alter_comment_time_alter_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
    ]
