# Generated by Django 4.2.6 on 2023-10-21 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_user_followers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-time']},
        ),
    ]
